language: cpp
sudo: required
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports
        packages:
        - cmake
        - cmake-data
        - g++-4.9
    env: CXX_COMPILER='g++-4.9'
install:
- cmake -version
- sudo apt-get install --yes doxygen graphviz
script:
- cmake -H. -Bbuild -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=Release
- cd build && make
- ctest
- cd -
after_failure:
- cat Testing/Temporary/LastTest.log
before_install:
- openssl aes-256-cbc -K $encrypted_6ba2bac98a17_key -iv $encrypted_6ba2bac98a17_iv
  -in bin/travisci_rsa.enc -out bin/travisci_rsa -d
- chmod 0600 bin/travisci_rsa
- cp bin/travisci_rsa ~/.ssh/id_rsa
after_success:
- ./bin/publish-doxygen.sh
